version: pending.{build}
max_jobs: 1


environment:
  GIT_DAEMON_PATH:   "C:\\Program Files\\Git\\mingw64\\libexec\\git-core"
  CYGWIN_GIT_PATH:   "C:\\cygwin\\bin;%GIT_DAEMON_PATH%"
  CYGWIN64_GIT_PATH: "C:\\cygwin64\\bin;%GIT_DAEMON_PATH%"
  PYTHON: "C:\\Python35"
  PYTHON_VERSION: "3.5.2"
  GIT_PATH: "%GIT_DAEMON_PATH%"
  CODACY_PROJECT_TOKEN:
    secure: mqO/RP09ekdyldmWCAUXfugtsAJSihpeR+EXMLheOzYCqd4yE45/FyHQhLfkR/Kx

matrix:
    fast_finish: true

init:
  - cmd: echo %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: appveyor UpdateBuild -Version "%APPVEYOR_REPO_BRANCH%.%APPVEYOR_REPO_COMMIT%.%APPVEYOR_BUILD_NUMBER%"

cache:
  - C:\Users\appveyor\AppData\Local\pip\cache
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%APPDATA%\pip\Cache'

install:
  - "%PYTHON%/Scripts/pip.exe install --disable-pip-version-check --user --upgrade pip"
  - "%PYTHON%/Scripts/pip.exe install --upgrade coverage"
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
  - "%PYTHON%/Scripts/pip.exe install codacy-coverage"
  - choco install gitversion.portable -pre -y
  - curl -O http://esrg.sourceforge.net/utils_win_up/md5sum/crc32.exe

before_test:
  - ps: C:\ProgramData\chocolatey\bin\gitversion /l console /output buildserver /updateassemblyinfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value
  - cmd: appveyor UpdateBuild -Version %GitVersion_InformationalVersion%.%APPVEYOR_BUILD_NUMBER%

test_script:
  - "%PYTHON%/python -m pytest --cov=utils --cov-config utils/tests/.coveragerc --cov-report xml -c utils/tests/.pytest"

after_test:
  - "%PYTHON%/Scripts/python-codacy-coverage.exe -r coverage.xml"

build: false

skip_tags: true

skip_branch_with_pr: true

